### ISSUE TITLE
Chargebee Integration

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#10]
@mrhegemon has a good idea of what the client wants who's paying for this feature add, so coordinate with him. We are keeping this mainbranch because payments with SSO  conneccted to Feathers is already a superhot featureset :)

**Comment by dmitrizagidulin** [comment]
@barankyle - do we need to do any more on this? (Should be mostly implemented, right?)

**Comment by barankyle** [comment]
@dmitrizagidulin There's a good deal more to do before it can be closed:

* Verify subscription through API instead of trusting that subscription ID passed as callback parameter is valid
* Support changing subscription level
* Support canceling subscriptions
