### ISSUE TITLE
Admin Control Panel

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#104]
Administrators should be able to edit everything in their server configuration and have it affect the whole cluster.

1. Set up React Admin in front end -- https://marmelab.com/react-admin/

2. If user is admin, add "Admin" option to user menu (dropdown from user name + icon in top right)

3. User view -- admin can list all users, or search by string, with a drop down for connected accounts (all, email, phone, github ID, etc)

Users can be banned, have their password reset, or their basic profile details changed -- admin can also view user's activity stream.

5. Create server-settings table to store server configuration values (server name, etc), seed with  current config if values don't exist in database

6. UI Panel -- parse all config options and make them available for admin to manage

**Comment by dmitrizagidulin** [comment]
Reassigning to @AyushiMastro (per conversation in chat with Liam and Shaw yesterday).
