### ISSUE TITLE
Run new installation of xr3ngine and QA issues encountered

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#1062]

**Comment by tarasprystavskyj** [comment]
I will help Tania to do that. And also try to record a screencast with comments on it. 
We will do installation for Sergiy today.

**Comment by tanya-vykliuk** [comment]
i've noticed just 1 bug(?) for me - i didn't installed docker-compose before - that's why, received an error when trying to run and start xr3ngine machine

**Comment by tanya-vykliuk** [comment]
sudo apt-get install build-essential
PYTHON=python3 yarn install --verbose

**Comment by tanya-vykliuk** [comment]
https://drive.google.com/file/d/1kWEhHfG1pYyEUrEJWa3DjvwKXA4WT6Bj/view
