### ISSUE TITLE
Editor -- on file upload, error: editor.map is not a function

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#1064]
https://drive.google.com/file/d/11rnjjjlPgunQX5R2rFwT-CdeJVqMK32X/view
@shawticus  as i see editor couldn't upload or understand that he already uploaded model file - that's why json is empty and can't map through it 
![Screenshot from 2021-01-14 15-58-49](https://user-images.githubusercontent.com/18659318/104600345-8b228f80-5681-11eb-862c-9afff0adcdee.png)

**Comment by tanya-vykliuk** [comment]
@shawticus please review if it's done on dev?
