### ISSUE TITLE
Faces error

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#1065]
When scene loads, gltf throws error about normal face direction, like this:

![Screenshot from 2021-01-14 01-08-17](https://user-images.githubusercontent.com/18633264/104569474-d0a17700-5605-11eb-8608-e61f2baa1431.png)

**Comment by tarasprystavskyj** [comment]
shaw.theoverlay.ethСьогодні о 16:17
Yes
I talked to Yarslav about faces error, he said it's harmless library thing
It looks ugly in code so we should definitely handle it, but for now it's okay
TBH we could wrap that code in try catch
And just throw the catch away

For faces error
try {
  // some code that is causing error
} catch (error) {
  // do nothing
}
