### ISSUE TITLE
Sometimes user spawns in controlling 2 characters

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#1081]
If a user connects twice and presses "join" on one client, they will spawn in with 2 characters, driving one. We need to kick the second client when the join button is pressed and prevent double-avatar from happening.

additionaly disable "join" button on click.

**Comment by tarasprystavskyj** [comment]
Andrew have seen it after loading second incognito tab together with first one. 
He healed it with closing and reloading browser and rebuilding a project. 

https://prnt.sc/wqxuol

**Comment by tanya-vykliuk** [comment]
https://drive.google.com/file/d/1QHAMs3OAuiH-ixmsmNwMrgj4-ltclsCy/view

**Comment by tanya-vykliuk** [comment]
https://drive.google.com/file/d/1aw7P2FYK6Ir_ZVqlhp4y4vPxfnLAirYc/view
![Screenshot from 2021-01-18 16-09-49](https://user-images.githubusercontent.com/18659318/104925700-d1406180-59a7-11eb-8ce7-916a9b7a084a.png)

**Comment by tanya-vykliuk** [comment]
as i get bug was because multiple press Loin World button - i've disable it after click
