### ISSUE TITLE
Friend Invite

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#133]
User can invite another user by email or phone number. If this user joins, an account will be made for them automatically with their phone or email used, and they will see the friend requests from their friend on creation.

**Comment by shawticus** [comment]
@green9016 This is sort of a copy of https://github.com/xrchat/xrchat-server/issues/132
We want to be able to invite users from SMS or Email.
If user doesn't respond immediately, (i.e. location doesn't exist), inform them that the location is no longer active, but they can add this user as a friend.
Before that, we should have a check if they are already a user in our system. If they are not, we should offer them the opportunity to create a new account (since they already magic linked, we can use their token and login from that so they don't need to magic link again)

**Comment by barankyle** [comment]
Implemented as part of #345.
