### ISSUE TITLE
Make sure external contributors are credited, add references to docs

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#1368]
Right now there are probably good chunks of the codebase which have lost attribution, are not formatted well, etc. Additionally, we're completely redoing our documentation engine and docs in general, and wherever our attribution page has gone is anyone's guess.

There are also sections where we started with one codebase but radically altered to it our own or switched solutions mid-stream, while there might not be code in the engine we should still add attributions to the docs.

We should do a full pass of the codebase to make sure that attributes are handled.

**Comment by robertlong** [comment]
Yeah I was just poking around and noticed there's no LICENSE for the whole Spoke codebase that's been dropped in here. I'd appreciate if that was added ASAP. Happy y'all got it working, but it's not ok to remove licenses.

**Comment by shawticus** [comment]
@robertlong yeah, I noticed we didn't have licenses in the spoke files and that was specifically what prompted me to write this issue, sorry about that, will have it fixed ASAP.

**Comment by robertlong** [comment]
Thanks, appreciate it :+1:

**Comment by shawticus** [comment]
Added LICENSE.md files for vendor code (as well as our own code, since that was missing from all the packages) but leaving this issue open because I want to figure out a way to make this more inclusive of individual contributors. I like how three.js has an @author tag, I think we can probably set that up so if someone goes through and marks who contributed in each file we can auto-generate that into our docs. I really want it to feel inclusive and created by all the people it's created by, not just "our thing" or whatever.

**Comment by robertlong** [comment]
Yeah this looks good: https://github.com/xr3ngine/xr3ngine/commit/3788f29702708010f2b1cccf99be6661f6c716bc

The `@author` tag is interesting, I totally forgot they had that. That's up to you. I think there are a bunch of ways to feature contributors whether it be in code or in a readme. I'm glad you included the license files in the repository for all of the dependencies though, so my concerns are addressed :+1:
