### ISSUE TITLE
Advanced User Settings

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#15]
GOAL:
A full stack solution -- API and front end menu -- so users can configure their avatar icon, connect and disconnect accounts and adjust settings.

(Should user settings and user profile be separate / separate related models)

**User Badge Menu and Profile Component**
In the front end, when you log in, there is a user badge and icon
When you click on the badge, it has a dropdown menu: profile, contacts, logout

If user clicks on profile: open a modal window where user can upload a profile photo (create and embed UserIcon component), edit their settings (create and embed UserSettings component) and connect additional accounts (embed existing "connect accounts" component our other engineer is building)

Details of settings require more review.

Planned so far.

**User Icon Component**
Upload / replace user icon
This is a "resource" of type "user-icon"
Add resource type to seed-config
Copy /upload-video pattern for user icon upload endpoint

**User Profile / Settings Component**
Enter room muted: true/false
Microphone volume: 0-100
Audio playback volume: 0-100
Visual Quality: High / Low
Use anti-aliasing: true/false

**Comment by dmitrizagidulin** [comment]
(Assigned to @AyushiMastro, in progress.)

**Comment by dmitrizagidulin** [comment]
(Partly implemented.)
