### ISSUE TITLE
Refactor config system, pull everything from ENV variables

### ISSUE THREAD

**Issue by dmitrizagidulin** [xr3ngine/xr3ngine#204]
* Deprecate the current system, which is a mixture of `dotenv` and  [`node config`](https://www.npmjs.com/package/config) / [`@feathersjs/configuration`](https://docs.feathersjs.com/api/configuration.html) system
* Pull in all configs via ENV variables
* Optionally, use [dotenv flow](https://www.npmjs.com/package/dotenv-flow) package to help manage the ENV vars.

**Comment by barankyle** [comment]
Implemented as part of #205
