### ISSUE TITLE
Realtime Instance Server MVP

### ISSUE THREAD

**Issue by dmitrizagidulin** [xr3ngine/xr3ngine#219]
We are building a realtime social MMO and plan to use tcp via sockets and udp via WebRTC data channels.

We want a realtime instance server as referenced in #221. This will be the the mvp of the agones backend.

Socket connection allows two users on the same server to see messages from the socket channel. Maybe to move a box around and see the movement of the other user's box.

**Comment by dmitrizagidulin** [comment]
Closing, duplicate of https://github.com/xr3ngine/xr3ngine/issues/221

**Comment by shawticus** [comment]
We have sockets and UDP comms. Enough to prove MVP, we will move to more detailed issues.
