### ISSUE TITLE
Hand Pose Tracking

### ISSUE THREAD

**Issue by dmitrizagidulin** [xr3ngine/xr3ngine#222]
We wish to be able to use input from computer vision tools to drive web AR and VR experiences.

Hand tracking offers us opportunities. 

1.  WebXR native.
Add WebXR and Touch Controls (being worked on now)
Hand Tracking in Oculus Quest
https://github.com/mrdoob/three.js/pull/19936 

2. For AR: Use an anchor point for AR content.

We want to do this to drive a Demo: A Volumetric Video asset playing in a hand. 

3. For a Character controller to drive hands/arms of a character.

https://github.com/stewdio/handy.js

Notes:
* Ask for example video
* https://storage.googleapis.com/tfjs-models/demos/handpose/index.html see if this can work with our volumetric player.  
* Look for a surface tracking solution that could work for android and ios
* https://twitter.com/golan/status/1266526826995822593?s=21

**Comment by mrhegemon** [comment]
Proposed plan and solution ~ 4 hrs (Maksym will do the task)
We should take one of libraries for 3d handpose detection (for example this library https://github.com/LingDong-/handpose-demos or one mentioned above) 
Assume that palm plane is build from three most static points marked red on image below
Place volumetric object on this plane, or in triangle center or in bounding circle center

No plan for surface tracking solution for android and IOS yet. Waiting for answers in discord.

**Comment by mrhegemon** [comment]
Goal is a demo that shows volumetric playback in the user’s hand. Will (@wildcapture ) has ideas on content, Piyush (@piyush) is working on volumetric playback and audio sync. Shaw can help with technical questions

Note: Please use Typescript and module syntax, ideally webpack or rollup to keep tracking code separate from demo code and extensible. We don’t need this for demo, but we will want to convert this to ECSY at some point.
