### ISSUE TITLE
Party CRUD + UI View

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#26]
Purpose of this feature:
This is like a "party" system in a video game. User A sends user B a request to join User A's party.

This might be expressed as a teacher and a class full of kids. When the teacher presses the button to enter a new world, it will instruct the kids to go with them into this room.

Step 1 -- Create the service (done)
Step 2 -- Associate with users
Step 3 -- Add to party, join party, remove from party and leave party
Step 4 -- Integrate with gameserver and instances for event messages like joining a new server.

Parties are small, ephemeral groups of users. There must be at least two people in a party for it to exist -- otherwise it is destroyed automatically.

Parties have their own chat, and party members can join each other's worlds. Party leaders can invite and kick party members from the party. When a party leader joins a location, every other party member will see an offer to join with them.

Party members can also join the room of any other member at any time, although the intention is that this feature will simplify helping groups all join the same room together.

**Comment by dmitrizagidulin** [comment]
@shawticus Excellent.
How do you feel about modeling this (or at least being able to export to) a vCard Group? (which means it'll sync natively with iOS and Android groups, etc)

**Comment by shawticus** [comment]
Sounds good to me

**Comment by shawticus** [comment]
Changed this so that group members all have an isLeader flag -- there is no 'owner' of the group.

We will need to review logic to delete the group when all members leave.

**Comment by shawticus** [comment]
@SaadAhmedSiddiqui when you've finished your current task, please take a look at this. We've redefined our models quite a bit and need to update the group assignment logic. I believe most of the group code is commented out.

**Comment by SaadAhmedSiddiqui** [comment]
@shawticus same for this!

**Comment by shawticus** [comment]
@barankyle please review

**Comment by dmitrizagidulin** [comment]
@SaadAhmedSiddiqui Is there a PR of the code in progress we can look at?

**Comment by SaadAhmedSiddiqui** [comment]
@dmitrizagidulin there is no PR for this because Step#4 is not completed yet

**Comment by dmitrizagidulin** [comment]
@SaadAhmedSiddiqui That's fine, can you please make a PR of the code in progress, before step 4?

**Comment by mrhegemon** [comment]
Review and close 
https://github.com/xr3ngine/xr3ngine/pull/168
https://github.com/xr3ngine/xr3ngine/pull/217

**Comment by barankyle** [comment]
Mostly implemented as part of #345. Parties work very similarly to groups. The requirement that there must be two people in a party has been ignored for now. Logic for invites to all party members to join a world hasn't been done since joining worlds is still in progress; a new issue should be created when we want to do that.
