### ISSUE TITLE
User Relationships / Friends

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#27]
Purpose of this feature:
We want users to have a basic friend list and ban list

Step 1 -- Users can add and remove other users and friends

Step 2 -- Users can block and mute other users

Step 3 -- Users can view the profile of other users

Step 4 -- Build front end component to reflect all of the API capabillities.

**Comment by SaadAhmedSiddiqui** [comment]
@dmitrizagidulin @shawticus  this issue is completed but the step 4 is not finished as we don't have Mockups and designs

**Comment by shawticus** [comment]
We have renamed this to "relationship". We also have relationship types, which to start are null, "friend" and "blocked". If a user sets a friend request, it creates a relationship with the initiator as userOne, a userOneRelationshipType to friend, the person who received the request is userTwo and their default userTwoRelationshipType is null.

Just needs to be tested and we can toss it in the done pile.

**Comment by shawticus** [comment]
@SaadAhmedSiddiqui This was heavily refactored (along with all of our other models), when you have a chance, please look at the logic / hooks for adding contacts. It may be commented out or not functional as a result of the models being changed.

**Comment by SaadAhmedSiddiqui** [comment]
@shawticus sure, i will update this and will ask if anything is unclear, 
Thanks for the update

**Comment by shawticus** [comment]
@barankyle please review

**Comment by dmitrizagidulin** [comment]
@SaadAhmedSiddiqui Is there a PR of the code in progress we can look at?

**Comment by SaadAhmedSiddiqui** [comment]
@dmitrizagidulin there was a PR but that is already merged

**Comment by barankyle** [comment]
Mostly implemented as part of #345. Friending and unfriending is present, blocking and muting currently is not. When we want to add blocking, we can make a new issue.
