### ISSUE TITLE
Group View + CRUD

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#288]
Users can belong to one or more organizations. Organizations can function like guilds in an MMO, with rank -- for example, recruit, jedi, master -- or they can be more typical for a real-world organization, like student / parent / teacher or developer / project manager / ceo.

1. Add "My organizations" view to user menu
2. User can CRUD organizations they own
3. Users can promote other users to organization owner
4. Users can invite other users to join their organization

**Comment by barankyle** [comment]
Mostly implemented as part of #345. Backend logic has been put in for group user rank 'admin', which would have power to invite and remove users but not change the group's name/description or delete the group, but has not been implemented on the front-end. Currently, only the owner can do any CRUD operations on the group itself or invite/remove users.
