### ISSUE TITLE
Add tests to verify that all APIs work on npm test

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#29]
Right now our services register that they work and exist, but that's it. We should add unit tests to validate the models, especially foreign key dependencies, via CRUD.

**Comment by shawticus** [comment]
@Vickyogesh This is important, but since most of our APIs are still under development we should not prioritize

**Comment by shawticus** [comment]
@Vickyogesh This would be a great next task now that most of our APIs are fairly solidified.

**Comment by Vickyogesh** [comment]
@shawticus @dmitrizagidulin any objection if I use chai for these tests ?

**Comment by shawticus** [comment]
@vinayqueppelin waiting on https://github.com/xrchat/xrchat-server/issues/142 for tests to pass CI

However, some of the tests are still failing locally. Please uncomment them all and make sure they work in the latest (something about userId failing) on dev branch.
