### ISSUE TITLE
Friends View + Friendfinding + CRUD

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#290]
We want users to be able to find their friends and manage their relationships.

This is a component that enables users to find a friend by searching for their email, phone, or connected account, and send a friend request.

Requested users will then be able to chat and invite each other to worlds (but this is a separate ticket).

**Comment by mrhegemon** [comment]
Basis of work:

https://github.com/feathersjs/feathers-chat
https://github.com/feathersjs-ecosystem/feathers-chat-react
TS https://github.com/micaelgallego/mediasoup-app/tree/master/customTypings

**Comment by mrhegemon** [comment]
Review and close 
https://github.com/xr3ngine/xr3ngine/pull/168
https://github.com/xr3ngine/xr3ngine/pull/217

**Comment by barankyle** [comment]
Mostly implemented as part of #345. We don't have text-based searching for friends, but users can invite people to be friends via email, SMS, or userId, and can remove friends, which will delete both directions of the relationship. Text search for friends can be a new issue.
