### ISSUE TITLE
User Notifications With Feathers Channels + Subscriptions

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#291]
The user will want realtime updates for events for the user.  These can be implemented universally using the Feathers channel feature and subscriptions.

https://blog.feathersjs.com/feathersjs-channel-subscriptions-647c771ca6c8
https://docs.feathersjs.com/api/channels.html

This will also need to interact with our Redux store, which also has the ability to send out messages to the user. Given that we may want to share these messages with components as state and they don't update very frequently, we can route them into Redux and use the existing notification system to show the user new messages or update flags on icons (similar to the login component messages).

This is for Vuex, but is conceptually similar:
https://blog.feathersjs.com/feathersjs-channels-vuex-7548fb5c5d2c

There is also a package for Feathers and Redux that might be helpful:
https://github.com/feathers-plus/feathers-redux

**Comment by barankyle** [comment]
Implemented as part of #345. There will assuredly be more cases where we'll need user notifications; the chat system is a good example of how to do it.
