### ISSUE TITLE
OPS: Set client_max_body_size on xrchat-server /upload endpoint

### ISSUE THREAD

**Issue by barankyle** [xr3ngine/xr3ngine#307]
The /upload endpoint will be handling large files. By default, nginx's max body size is 1 MB, which is way too small for most files. It should be set to 1000M.

**Comment by shawticus** [comment]
@barankyle can we close this? or how do we fix?

**Comment by barankyle** [comment]
We can close it. It's now specified in the Helm values files, currently at 5 MB, but it's trivial to change if we need to set it higher.
