### ISSUE TITLE
UI / DOM Event Input Binding

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#403]
We want to bind events from the UI (like buttons) to actions

User Presses Button
Button is handled by DomEventInputSystem (or similar name)
Input is mapped to action and axis like keyboard and mouse

**Comment by alexander-shvets** [comment]
Done, in [InputSystem](https://github.com/xr3ngine/xr3ngine/blob/b821e84f674d1bb17deccea3beb8311733e77732/packages/engine/src/input/systems/InputSystem.ts#L58):
```js
const schema = {
  eventBindings: {
    click: [{
        selector: '#myButonId',
        behavior: rotateStart,
        args: {}
    }]
  }
}
```
@shawticus please review & close.
