### ISSUE TITLE
EffectPass rendering is very heavy, even with empty passes

### ISSUE THREAD

**Issue by XiaNi** [xr3ngine/xr3ngine#415]
this is what we have with enabled empty EffectPass
a pair of script executions and a lot of GPU work
![image](https://user-images.githubusercontent.com/273573/90915024-8108a780-e3e7-11ea-8e49-e451f5ffb101.png)

and this with disabled
a lot of script executions and some GPU calls
![image](https://user-images.githubusercontent.com/273573/90915209-d04ed800-e3e7-11ea-8cea-b34f38e04eae.png)

**Comment by alexander-shvets** [comment]
Probably, I've fixed this:
https://github.com/xr3ngine/xr3ngine/pull/428/commits/2e13250df273b15018d3d40509ccd489e5eeeb1e
