### ISSUE TITLE
Player List + Bind ECS State to Redux

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#423]
At the high level, we need to bind our React UI to our ECS state and vice-versa. Right now our application state is managed by Redux. Redux and our ECS system are both ways of managing global state and reacting to it-- the ECS system has onChanged events and we are going to need to implement observables in our networking.

So we have a few high-level options:
1. copy data from ECS to Redux to trigger observables and UI state updates through Redux, 
2. save all of our current ECS state in redux, Engine state becomes just another redux store
3. Remove redux and have out entirely application run on observable state in ECS, maybe using MobX observables or a similar state library (https://github.com/aweary/react-copy-write ?)

I am most concerned about 1. performance and 2. simplicity for developers in learning systems and managing state. For someone porting an existing React application to spatial, option #1 and #2 might be best for existing websites trying to migrate to spatial, option #3  is most interesting to me because ECS and Redux are very similar and using an ECS system to manage state for the whole application would make a lot of game dev types very happy.

Our goal is to create a React component that gets an updated list of connected players and allows the current user to select their name and block or unblock them, which will hide that player's prefab. The goal here isn't to execute all functionality in the player block lifecycle, but to have bidirectional state updates from engine to UI and back.

**Comment by alexander-shvets** [comment]
Yes, I have some thoughts, ideas about this...
1st important thing, that I read [here](https://habr.com/ru/company/2gis/blog/498638/):
Store should not be immutable

**Comment by alexander-shvets** [comment]
@shawticus 
>> 2. save all of our current ECS state in redux
ECS state is very dynamic, it will be hard for redux to manage up to 60-90 updates per second.
>> 3. Will be a problem, if user will pause all world, then how hi can start it back? Should be other, UI world, to start/pause the game?

**Comment by alexander-shvets** [comment]
>> Our goal is to create a React component that gets an updated list of connected players and allows the current user to select their name and block or unblock them, which will hide that player's prefab. The goal here isn't to execute all functionality in the player block lifecycle, but to have bidirectional state updates from engine to UI and back.

@shawticus 
The list comes from websocket?
How to hide player's prefab? Call onDestroy behaviour?
