### ISSUE TITLE
Replace as many lodash calls with native solutions as possible

### ISSUE THREAD

**Issue by barankyle** [xr3ngine/xr3ngine#426]
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore

**Comment by alexander-shvets** [comment]
maybe, we can automate it?

https://github.com/kevinbarabash/codemods

https://github.com/eschaefer/codemod-get-to-optional-member-expressions
https://webuild.envato.com/blog/automating-the-migration-of-lodash-to-lodash-es-in-a-large-codebase-with-jscodeshift/
