### ISSUE TITLE
User can zoom camera in and out

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#464]
Right now we are at a fixed distance. Current is good for default, want to be able to zoom in a little closer and a little bit farther. This is middle mouse button for desktop and pinch mobile probably.

**Comment by XiaNi** [comment]
should we also use scroll for this?

**Comment by XiaNi** [comment]
Camera distance change implemented by mouse scroll.
@ANDFEWD we need camera zoom on touch screens

**Comment by ANDFEWD** [comment]
Issue is still relevant due to the fact that camera zoom on touch screens is still in progress
