### ISSUE TITLE
Set Envmap for Imported Models

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#465]
Long term, we want to have an environment set per scene (if we want more granular eventually we can do environment areas, but for now we should have one global). In lieu of a scene load, we should have a default environment map in public assets that is attached to our Scene component that all loaders can look for.

For our current demo, the easiest way to do this is to put an environment map in our public assets, reference it on one of our singleton components and have our loaders grab it. We can worry about per-scene later, I assume when a scene loads it will just change the world environment map to the current scene's.

**Comment by XiaNi** [comment]
as i know scene.environment is used when no envMap is set on material, by default it works at least with cubemap loaded envmaps.
https://threejs.org/docs/#api/en/scenes/Scene.environment
