### ISSUE TITLE
Character Selection + Separated Animation

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#474]
Currently, we have a single actor with packed animation takes. Eventually we will want to be able to change skins without having to pack all of the animation into each skin.
This task is broken up into 3 parts:
1. apply animation to any of the characters in the /public/models/avatars folder from the animation glb in that same folder
2. Randomly choose one of the characters when the user joins the world (this is temporary behaviors for demos and will change later)
3.When user joins, show a character selector, similar to overwatch, etc.

From here we will probably move to inventory and a more complex setup, but for many worlds and users, especially guests, this will probably be the default interface to start with.

**Comment by Ryuno-Ki** [comment]
Perhaps worth to attach a screenshot of Overwatch (for those who don't know what it is + as long as you can get pictures of it).
