### ISSUE TITLE
Input system: block event listeners on some elements, like UI or Inputs

### ISSUE THREAD

**Issue by XiaNi** [xr3ngine/xr3ngine#568]
Currently when you type in something in input - character reacts to input, same for mouse move over UI elements, even something like 'blocker'.

possible solution:
in `packages/engine/src/templates/shared/DefaultInputSchema.ts`
use `element` in `eventBindings` behavior values, like
```ts
    mousedown: [
      {
        behavior: handleMouseButton,
        element: 'viewport', // 'viewport'|'document'|'window'
        args: {
          value: BinaryValue.ON
        }
      }
    ],
```
`mousedown`, `touchstart` - this listeners should be bound on 'viewport' only

`keyup`, `keydown` - this listeners should be set to 'document' but we need to block them if `event.target` is input element.
probably inside `packages/engine/src/input/behaviors/handleKey.ts`

**Comment by ANDFEWD** [comment]
@shawticus This task is completed and already merged in to dev branch (ie the user can type text in the input and move the mouse on pop-ups without interacting with the scene). The only nuance is that not all cases can be predicted, I think it should be tested from a UX approach. 
If I do not speak clearly, then feel free to contact me about it.

**Comment by shawticus** [comment]
I will close it for now. There are a lot of little UI things that we'll need to approach later, if it's an issue we can make another ticket.
