### ISSUE TITLE
Input .started event not properly executing

### ISSUE THREAD

**Issue by tanya-vykliuk** [xr3ngine/xr3ngine#585]
If add behavior listener like this, on `started`:
```ts
const InputComponent = getMutableComponent(actorEntity, Input);
InputComponent.schema.inputAxisBehaviors[DefaultInput.LOOKTURN_PLAYERONE] = {started : [{behavior:actorLooked}]};
```
it's not catched on flight for touch

but it works with `changed`:
```ts
const InputComponent = getMutableComponent(actorEntity, Input);
InputComponent.schema.inputAxisBehaviors[DefaultInput.LOOKTURN_PLAYERONE] = {changed: [{behavior:actorLooked}]};
```

**Comment by tanya-vykliuk** [comment]
the same with 
    InputComponent.schema.inputAxisBehaviors[DefaultInput.MOVEMENT_PLAYERONE].changed.push({behavior:actorMoved});

if started - then not catch movement with nipple

**Comment by shawticus** [comment]
Following up with this, is this still an issue? @ANDFEWD @tanya-vykliuk

**Comment by tanya-vykliuk** [comment]
@shawticus it works with changed  (not with started but works). I believe it's bug - but maybe not critical for now.

**Comment by shawticus** [comment]
We can tackle it next week. We shouldn't have bugs like that in the code, but if it's not currently harming us we should focus on what the user will see.

**Comment by XiaNi** [comment]
looks like it's not really a bug, since axis could be changed/started earlier so axis.started is hard to catch, it's fired once per page load.
