### ISSUE TITLE
Camera drag sticks to mouse if not ended inside of document

### ISSUE THREAD

**Issue by XiaNi** [xr3ngine/xr3ngine#589]
1. mouse down
2. mouse move out of document (for example to chrome debug console)
3. mouse up
4. mouse move back into document

camera will still follow mouse, probably we should "end" mouse buttons on mouse leave window/document

**Comment by shawticus** [comment]
I've noticed this is also an issue inside of orbit controls in THREE. We need to say "if mouse is down, and there is no event at all for .25 seconds, call mouseup" or something like that.
