### ISSUE TITLE
test/onboarding styling

### ISSUE THREAD

**Issue by tanya-vykliuk** [xr3ngine/xr3ngine#596]

**Comment by tanya-vykliuk** [comment]
-added lightTheme/darkTheme - just comment/uncomment defaul export; 
-change dialog/snackbar width for mobile/desktop; -added Razerlaptop to test/interactive, test it;
-change infoBox from div to Dialog Materialui component(to reuse common theme style);
-separate scene for interaction(with RazerLaptop, toolpit, infobox and mobilegamepad)

**Comment by shawticus** [comment]
Is this completed? Can I close? I believe we will need to do a more thorough style and QA pass once everything is working together, so we should just focus on any functionality / housekeeping for this ticket.

**Comment by mrhegemon** [comment]
We need to go back and fix the onboarding style. Do we only have a white scene?

Consistent size on desktop
30% wide, 50% high on desktop.

75% wide, 75% high on mobile.

Refer to the wireframes.

**Comment by tanya-vykliuk** [comment]
we have light and dark theme - they both lives in theme.tsx file. We talk in future select one of them according to scene type(light/dark)
