### ISSUE TITLE
Change theme to light

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#608]

**Comment by tanya-vykliuk** [comment]
-added lightTheme/darkTheme - just comment/uncomment defaul export;

**Comment by tanya-vykliuk** [comment]
https://github.com/xr3ngine/xr3ngine/issues/608 - still in progress
@shawticus i can't figure out how to color images - can you look please - packages/client/components/ui/OnBoardingBox/index.tsx - line 123
and can't rewrite fontFamily in theme packages/client/theme.tsx - line 139
