### ISSUE TITLE
Location admin view has a "scene selection" which connects scene to location

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#611]
Related to #610

When we launch a location we want to be able to select from a list of available scenes -- these will be the scenes that are marked public or that the user owns. We will then fetch the location separately from the scene.

**Comment by shawticus** [comment]
Not sure I'm thinking about this properly. We need our /location route to get the location, then get the scene Id from that. It currently doesn't do that, but it does set the scene ID when it provisions the location ID, so we almost have everything we need... will work on this more when I'm not tired, but for now work is pushed into dev to provision with the sceneId provided by the user when they try to connect to the scene... but this seems wrong...

**Comment by shawticus** [comment]
@barankyle I believe this can just be added to one of your drawers-- if a user wants to create a new location, they can set the alias, permissions, etc etc-- they just also need to be able to set the scene ID. The scene needs to be from the list of projects, in the same way /location/[projectId].tsx loads the project.

There is a confusing thing where our model for project and scene are the same, but the services are not, in this case we are keeping project and will probably remove scene and rename project to scene, but for now, project.

**Comment by barankyle** [comment]
Implemented in #651
