### ISSUE TITLE
Set camera position and rotation to scene preview camera when client joins, before avatar instantiates.

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#617]
In the editor, we can create a "scene preview camera" which sets the preview screenshot, and can also give us a place to position the camera when the player joins the scene. Once their avatar instantiates, we want the camera to lerp over into position.

**Comment by tanya-vykliuk** [comment]
passed branch for proceed to @XiaNi  - https://github.com/xr3ngine/xr3ngine/tree/617-camera-start-position
