### ISSUE TITLE
Merge all UI from development routes into pages/location/[sceneId]

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#622]
CONTEXT:
Currently there is no UI in the multiplayer scene loading route, which is going to be  our public route. This is at https://localhost:3000/location/<sceneId> or, in the project, and @xr3ngine/packages/client/pages/location/[sceneId].tsx

DELIVERABLES:
Copy and consolidate all of the UI and input development into the location route.
Remove any stale or unnecessary routes for development, unless you feel it is valid to keep them for continued development.

**Comment by tanya-vykliuk** [comment]
i have to add onboarding/tips/gamepad etc into location?

**Comment by tanya-vykliuk** [comment]
https://github.com/xr3ngine/xr3ngine/pull/637

**Comment by tanya-vykliuk** [comment]
https://drive.google.com/file/d/1b_8E1DUWpYg_mQthAY5eWc3DnyNNQp2P/view
