### ISSUE TITLE
Website Development + Design

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#628]
CONTEXT
We have a new developer coming on board to help share some of the load. One thing we really need to move forward is a strong website that is integrated with our core app, so that our users can experience the product as part of our overall pitch. An example of this is webaverse.org or dotbigbang.com, where the lander and app feel seamless.

We have some wireframes, but these need to be cleaned up, signed off on by everyone for message and product, and passed on to the designer. In the mean the our developer can start developing from finished wrireframes.

DELIVERABLES
1. Oversee completion of wireframe in Figma with filler text and placeholder images
2. Pass wireframe and notes to UI designer and developer.
3. Replace filler with final copy and get approval from stakeholders.
4. Coordinate final assets with design and development, and oversee design -> development is going smoothly.

**Comment by VR-Nima** [comment]
Currently outlining the dev plan in Confluence for XREngine.io and [MyXR.social](https://xrengine.atlassian.net/wiki/spaces/XRS/pages/35979302/MyXR.social+Site+1.0).

I agree with @mrhegemon that we should develop these two in Squarespace, no benefit it rolling them custom right now.

I've requested access from Liam and will begin dev once there's consensus on the site Spec in Confluence and access is granted on Squarespace.
