### ISSUE TITLE
Bug with touch control of the camera

### ISSUE THREAD

**Issue by ANDFEWD** [xr3ngine/xr3ngine#634]
The touch control of the camera works intermittently and not quite correctly. The reason is most likely that the position of touch has time to change in the time between executions.

The bug is shown in the video attached below
https://youtu.be/BXPX_U0j4qA

**Comment by shawticus** [comment]
@XiaNi @ANDFEWD what's the status on this issue, and who's responsibility should it be?

**Comment by XiaNi** [comment]
@shawticus i didn't worked on this yet. and didn't check if i can reproduce.
