### ISSUE TITLE
Add .5-1 second delay to each tutorial card transition

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#656]
Right now, when the user clicks or press E or any of the tutorial interactions, the card switches immediately. We want to give a brief delay (.5 seconds to start) before the tutorial card changes, and then fade out / fade the next tutorial card in.

**Comment by tanya-vykliuk** [comment]
here i will delete avatar selection step from onboarding process

**Comment by tanya-vykliuk** [comment]
@XiaNi @shawticus  - maybe you have some tips/tricks/suggestions why it's act like this?
https://drive.google.com/file/d/1SwuTaLJ-_O2t42qHppCH45HX0PVWjpvd/view - ugly way but it works properly with fading in/out (packages/client/components/ui/OnBoardingBox/index.tsx - rows 40,47)
https://drive.google.com/file/d/1j4oEBmkaEq0ZeNy-g_8XRVV4UQSJ69nJ/view - normal way - but works without transition (packages/client/components/ui/OnBoardingBox/index.tsx - rows 42, 49)

**Comment by tanya-vykliuk** [comment]
@shawticus it's already done
