### ISSUE TITLE
Loading UI Design + Theme

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#664]
<img width="932" alt="Screen Shot 2020-11-15 at 1 02 14 PM" src="https://user-images.githubusercontent.com/18633264/99196731-1e534d80-2743-11eb-85e3-1e5639882f27.png">

**Comment by tanya-vykliuk** [comment]
![image](https://user-images.githubusercontent.com/18659318/99775330-cb4d1200-2b17-11eb-88e8-e9673015e4f3.png)
