### ISSUE TITLE
Interactable component in editor

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#668]
CONTEXT
We want to make objects interactive, but we want to do this from inside the editor.

DELIVERABLES
1. Add "interactable" checkbox and options for interaction type, etc to gltf model type in editor
2. Handle interaction code properly, combining our existing code with the editor to change and store serialized values.
3. Clean up and prepare for Showroom demo where we have ~16 interactables to load in.
4. We will need to maintain the same parsing from glTFs that we have for cars, etc.

**Comment by XiaNi** [comment]
@shawticus i think car should be added or as additional node, like CarNode or as "component"/checkbox to ModelNode, coz it have it's own physics setup, etc.
