### ISSUE TITLE
New Avatar Selection Component

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#676]
<img width="932" alt="Screen Shot 2020-11-15 at 1 02 07 PM" src="https://user-images.githubusercontent.com/18633264/99196716-0c71aa80-2743-11eb-9e56-9b2bb20b569b.png">

**Comment by shawticus** [comment]
![Uploading Screen Shot 2020-11-15 at 12.56.28 PM.png…]()

**Comment by tanya-vykliuk** [comment]
@shawticus  - when user clicks on Avatar icon - he see the avatar updated on scene - what should have happened when he clicks CHANGE ? in auth service i found function for uploadAvatar and inside dispatch(avatarUpdated(result)); - but i'm not sure that this is what should've happened here
![image](https://user-images.githubusercontent.com/18659318/99509572-982b4700-298e-11eb-841d-a53312625064.png)
![image](https://user-images.githubusercontent.com/18659318/99510048-40d9a680-298f-11eb-9d97-683f3e9480f4.png)
