### ISSUE TITLE
skybox optimization

### ISSUE THREAD

**Issue by XiaNi** [xr3ngine/xr3ngine#687]
now we have skybox as geometry, box for sky shader and cube map, sphere for equirectangular.
bad side of such practice is that we should have camera.far to really see sky geometry.

we can do two ways:
1. generate static image from shader and use it as environment map
2. may be we can convert it to shader pass and use as background, Sky chader should not be a problem, but cube map and equirectangular should be found, or written from scratch.

**Comment by shawticus** [comment]
@XiaNi I have assigned @ANDFEWD the task of setting the skybox in the editor to be image-based.

According to this:
https://threejsfundamentals.org/threejs/lessons/threejs-backgrounds.html

We can do the code like this:
```
    const loader = new THREE.CubeTextureLoader();
    const texture = loader.load([
      'pos-x.jpg',
      'neg-x.jpg',
      'pos-y.jpg',
      'neg-y.jpg',
      'pos-z.jpg',
      'neg-z.jpg',
    ]);
    scene.background = texture;
```

I'm not sure about equirectangular-- I'm thinking that we will run the equirectangular-to-cubemap conversion of 5-6 cubemaps and provide those as options to the user.

**Comment by XiaNi** [comment]
@shawticus you right!
and equirectangular is even easier:
scene.background = new TextureLoader().load('/someimage.png')
this and cube background will cover 2/3 of what i described, just forgot that scene has background option =)
