### ISSUE TITLE
Guest -> Logged in User Flow

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#727]
CONTEXT
Right now, when a user joins they get a guest account.

We want them to be able to log in to retrieve their existing account details.

1. If user logs in with Google and already has an account tied to google, switch them to that user and delete their guest account.

2. If user logs in with Google and does not already have an account, add a connected account to their guest user account (upgrade)

3. If user logs in with Google, we want them to be able to disconnect providers and delete their account completely (in the account settings)

**Comment by barankyle** [comment]
Implemented in #811
