### ISSUE TITLE
scene components json fields are strings

### ISSUE THREAD

**Issue by XiaNi** [xr3ngine/xr3ngine#750]
scene components have fields with encoded json data, they should be parsed as objects but now it's broken
![image](https://user-images.githubusercontent.com/273573/100075206-56941380-2e48-11eb-9761-52ff6637ee81.png)

**Comment by XiaNi** [comment]
change that causing this bug was made in:
https://github.com/xr3ngine/xr3ngine/commit/cfff918d1fe52d997e41629e6d564268ef626f55#diff-01d9ac9702b106fc360abfaae495652c239646e4e930263a86a8c898629c6785
in `packages/server/src/models/component.model.ts`
`return JSON.parse(data);` was replaced by `return data;`
i think we should add regexp check that if data is something like `{.*}` then parse, otherwise return as is?

**Comment by barankyle** [comment]
Fixed, with an additional check that data is a string before running .match, in #755.
