### ISSUE TITLE
Debug Join World Flow

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#778]
Right now when the client connects, things are messed up. This might be because something was merged that should not have been, or was merged incorrectly.

As a result, the /location route never gets beyond the loading screen, even though it seems to load the world correctly. The user isn't receiving an avatar. For now I've changed the SocketWebRTCClientTransport back to using JoinWorld, which at least gets us into the world. However the camera seems not not be oriented correctly for scene preview, and isn't connect to the avatar when we're in the world.

**Comment by XiaNi** [comment]
closed with #824
