### ISSUE TITLE
Move Login to menu (not modal) and add Oauth login options

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#779]
Right now the login in the menu is a modal. Instead, let's embed the component directly into the menu.

Also, we want to let the user log in with email or with oauth (Google, Facebook). We will improve the design on this, but for now having tabs to switch between the two or email and oauth stacked on top of each other is fine.

**Comment by tanya-vykliuk** [comment]
@shawticus for now in next/config we have defined data 
`enableFacebookSocial: false
enableGithubSocial: false
enableGoogleSocial: false`
so this tab hidden in login page, but if redefine this values to true it will look like this 
![image](https://user-images.githubusercontent.com/18659318/100753737-dbf06880-33f2-11eb-8e12-649842294409.png)

![image](https://user-images.githubusercontent.com/18659318/100753789-e90d5780-33f2-11eb-966b-18ceab6e73cf.png)
