### ISSUE TITLE
Move WebRTC Video start button to input component

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#801]
Right now we have a + that starts the video. We want to move this functionality to our audio/video component.

We want to be able to start audio without video by clicking on microphone, or video with audio by clicking on camera icon. We might need to consult Mediasoup API for this. Kyle might also be able to help.

**Comment by barankyle** [comment]
The workflow should be like this:

1. The VideoChat button will be going away, as we don't want a separate button for starting/ending the user's audio/video producers. 

2. When the user first joins a scene, audio and video should be muted in mediaIconsBox. When they click on either one, that should kick off most of the logic in client/classes/transports/WebRTCFunctions -> sendCameraStreams. The client ensures that it has a mediaStream from which to get audio and/or video, then ensures that it has a sendTransport and receiveTransport for the party/instance, creating them if necessary. It then makes a video or audio producer.

3. If the other media type is unmuted and there's no producer for that type, create a producer. 

4. If both a video and audio producer are present, and one of the mediaIcons is clicked and muted, the corresponding producer should be paused. If that mediaIcon is clicked again, the corresponding producer should be unpaused.

5. If one is muted and the other mediaIcon is clicked to mute it, we should call WebRTCFunctions -> endVideoChat. The producer(s) should be deleted* and the user will leave the call. *There may only be one producer present, if the user just started audio and then muted audio, for example; skip deleting the other producer if it's null

6. Un-'muting' after leaving the call will go back to #2 above.
