### ISSUE TITLE
Fix colorspace of avatars

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#847]
Our avatars look really dark and poorly colored in engine. This is definitely a color space issue with how we are importing the assets.
- Determine if we need to re-export or can fix in code
- If in code, fix color space
- Otherwise push to dev team to get new models

**Comment by XiaNi** [comment]
this sphere has same material as avatar, except without texture and color is one i took from texture, or skin or reddish patch... anyway it's not same color as avatars skin.
![image](https://user-images.githubusercontent.com/273573/102184901-e281e400-3eb8-11eb-8c5a-9649047688f4.png)

**Comment by XiaNi** [comment]
@shawticus i got it, it's texture.
![image](https://user-images.githubusercontent.com/273573/102185739-3214df80-3eba-11eb-846f-67c86a5969de.png)
nearest one is using texture that i'v extracted from blender and loaded like new texture after loading file.
like this
```ts
            args: {
                component: AssetLoader,
                componentArgs: {
                    url: "/models/debug/rose.glb",
                    onLoaded: (o,x) => {
                      console.log('Loaded ROSE === ', o, x);
                      x.asset.children[2].material.map = new TextureLoader().load('/textures/9_meshes_Merge_Diffuse.jpg');
                      x.asset.children[2].material.map.flipY = false;
                      x.asset.children[2].material.needsUpdate = true;
                    }
                }
            }
```

**Comment by XiaNi** [comment]
solved adding LinearTosRGB effect to postprocessing scheme
