### ISSUE TITLE
Fix And Test Video and Audio

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#860]
When we added functionality for the top video buttons to handle connection we lost the auto-connection that lets us see other users.

- Test two video windows together -- can users see each other?
- User A should see user B, even if user A doesn't have camera on
- When user turns video on, do not turn on audio
- Remove blue + button that inits calls
- Make sure connection works for multiple and flow feels "fast"

**Comment by tanya-vykliuk** [comment]
![Screenshot from 2020-12-10 15-51-00](https://user-images.githubusercontent.com/18659318/101781324-51012380-3b00-11eb-86b7-07adc20b0797.png)
![Screenshot from 2020-12-10 14-11-02](https://user-images.githubusercontent.com/18659318/101781330-52325080-3b00-11eb-8d1c-5aa21b16c04e.png)
![Screenshot from 2020-12-10 13-59-38](https://user-images.githubusercontent.com/18659318/101781332-52325080-3b00-11eb-87bf-46f47cc3ace2.png)

**Comment by tanya-vykliuk** [comment]
Now i see this issues when connect from 2 browsers ^ @barankyle
