### ISSUE TITLE
User Name Plate

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#881]
CONTEXT
When the user joins the world we want to add a nameplate object that can be enabled, disabled and fade in and out. 

DELIVERABLES
- The nameplate is always above the user's head, but always facing the lower user
- Nameplate changes when user changes name

**Comment by ANDFEWD** [comment]
Actually in first version I made this plate using three.js and troika-three-text lib, but it bugs a lot and was hard to maintain , so in a course of conversation with @XiaNi and @shawticus we decide use React component instead.
