### ISSUE TITLE
Microphone and camera icons optimization

### ISSUE THREAD

**Issue by ANDFEWD** [xr3ngine/xr3ngine#917]
The microphone and camera icons should depend on the location settings in the admin panel
Currently the microphone and camera icons on the location are not displayed dynamically (they are fixed), regardless of whether the user has enabled the audio or video option for this location in the admin panel(https://localhost:3000/admin). 
I think it is advisable to connect these things so that no mistakes occur in the future.

**Comment by tanya-vykliuk** [comment]
Just Audio
![image](https://user-images.githubusercontent.com/18659318/102984404-35414880-4516-11eb-897c-104ec632f8c5.png)
![image](https://user-images.githubusercontent.com/18659318/102984303-10e56c00-4516-11eb-8909-a2a911a084c5.png)
Just Video
![image](https://user-images.githubusercontent.com/18659318/102984704-a254de00-4516-11eb-8471-66cb87f105e3.png)
![image](https://user-images.githubusercontent.com/18659318/102984649-8cdfb400-4516-11eb-8f92-fda82b44c758.png)
Nothing
![image](https://user-images.githubusercontent.com/18659318/102984734-b13b9080-4516-11eb-9eee-5506f26d889e.png)
![image](https://user-images.githubusercontent.com/18659318/102984817-da5c2100-4516-11eb-8c96-d8738b23f57c.png)
All
![image](https://user-images.githubusercontent.com/18659318/102984873-eea01e00-4516-11eb-8325-5b3feeee3f1a.png)
![image](https://user-images.githubusercontent.com/18659318/102985336-ae8d6b00-4517-11eb-8735-6a18828ed3a9.png)
