### ISSUE TITLE
Smooth out client side prediction

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#981]
Right now character is pretty stuttery in dev server.

Once local packet loss and latency have been setup, take steps to tune network interpolation time / # names and any lerp values to try to smooth out movement.

**Comment by HydraFire** [comment]
have a bug, I thought this twitch was due to the server correction. There is nothing. Server correction also needed to be improved(done). But the bug still remained, I am looking for its cause in physics itself and velocity and fixed time step.
