### ISSUE TITLE
User + Party + Group Messaging

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#99]
User should be able to manage chats with their current group, any organizations they are a part of and any private chats they may have open.

Each collection of chats (group, organization, friends) is grouped and can be collapsed or expanded. The most recent conversations are shown. The rest can be expanded with a (more...) button. 

NOTE: Parties are ephemeral. A user can only be in one party. Groups are like guilds or organizations in other games, except that a user can be in more than one organization at a time.

Check out Feathers Channels, look at the /graphql endpoint and playground and thing about the best way to handle realtime message updates.

Party chat should be stored with the party, and removed when the party is destroyed (users = 1).

Group chat should be available to all group users, similar to a WhatsApp or Telegram group conversation.

-- Work with @syedsimanta03 to make sure all features and functionality are in sync between design prototype and backend.

-- Work with @Harendraqueppelin  to integrate backend chat functionality to frontend.

**Comment by mrhegemon** [comment]
Basis of work:

https://github.com/feathersjs/feathers-chat
https://github.com/feathersjs-ecosystem/feathers-chat-react
TS https://github.com/micaelgallego/mediasoup-app/tree/master/customTypings

**Comment by mrhegemon** [comment]
Review and close 
https://github.com/xr3ngine/xr3ngine/pull/168
https://github.com/xr3ngine/xr3ngine/pull/217

**Comment by barankyle** [comment]
Implemented as part of #345.
