### ISSUE TITLE
Each avatar references it's own animation set

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#993]
Right now, all avatars are using the same animation. We want to have separate male and female animations, and eventually allow animation sets to be specific to avatars.

In the animation manager, we are currently loading Animation.glb -- this should instead be loaded on the avatar, which checks if that file has already been loading (animation manager should have an animation cache?) and loads or pulls from cache.

Currently, the Animation.glb file is hardcoded into the animation manager.

![Screenshot from 2021-01-04 08-56-22](https://user-images.githubusercontent.com/18633264/103559521-1ffbe080-4e6b-11eb-86f6-7bfe1b382e61.png)

┆Issue is synchronized with this [Jira Task](https://laguna.atlassian.net/browse/XR3NGIN-19) by [Unito](https://www.unito.io/learn-more)

**Comment by tanya-vykliuk** [comment]
@shawticus where i should get this different animations? - now yes, we use universal animation set - for every character. You want to connect specific animation to avatar - how to do this? in editor or in some config?
